; Generated NSIS script file (generated by makensitemplate.phtml 0.21)
; by 152.7.43.119 on Mar 19 02 @ 17:20

; NOTE: this .NSI script is designed for NSIS v1.8+

Name "JAdvisor"
BrandingText "JAdvisor v0.4.6"
OutFile "jadvisor-0.4.6-install.exe"

; Some default compiler settings (uncomment and change at will):
; SetCompress auto ; (can be off or force)
; SetDatablockOptimize on ; (can be off)
; CRCCheck on ; (can be off)
; AutoCloseWindow false ; (can be true for the window go away automatically at end)
 ShowInstDetails show ; (can be show to have them shown, or nevershow to disable)
; SetDateSave off ; (can be on to have files restored to their orginal date)

LicenseText "You must agree to this license before installing."
LicenseData "jadvisor\license.txt"

InstallDir "$PROGRAMFILES\JAdvisor"
InstallDirRegKey HKEY_LOCAL_MACHINE "SOFTWARE\JAdvisor" ""
DirShow show ; (make this hide to not let the user change it)
DirText "Select the directory to install JAdvisor in:"

Section "" ; (default section)
SetOutPath "$INSTDIR"
File /r "jadvisor\*" ; add files / whatever that need to be installed here.
;WriteRegStr HKEY_LOCAL_MACHINE "SOFTWARE\JAdvisor" "" "$INSTDIR"
SectionEnd ; end of default section

Section "Start Menu Shortcuts"
  CreateShortCut "$SMPROGRAMS\JAdvisor.lnk" "$INSTDIR\jadvisor.bat" "" "$INSTDIR\bin\icons\ja.ico" 0
SectionEnd

; eof
